# Generated by Django 5.0.2 on 2025-10-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetatmoStation',
            fields=[
                ('device_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('height', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'netatmo_stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'stations_data',
                'managed': False,
            },
        ),
    ]
