# Generated by Django 5.0.2 on 2026-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationMonthAvg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.CharField(max_length=64)),
                ("year_num", models.SmallIntegerField()),
                ("month_num", models.SmallIntegerField()),
                ("h3_res_5", models.TextField(blank=True, null=True)),
                ("h3_res_7", models.TextField(blank=True, null=True)),
                ("h3_res_9", models.TextField(blank=True, null=True)),
                ("avg_temp_all", models.FloatField(blank=True, null=True)),
                ("avg_temp_v1", models.FloatField(blank=True, null=True)),
                ("avg_temp_v2", models.FloatField(blank=True, null=True)),
                ("avg_temp_v3", models.FloatField(blank=True, null=True)),
                ("avg_temp_v4", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "station_month_avg",
                "managed": False,
            },
        ),
    ]
